name: Firebase Deploy

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install # or yarn install

      - name: Build Vite app
        run: npm run build # or yarn build  <--- This is essential!

      - name: Install Firebase CLI
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: hosting:disable # Optional

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}